espn_scoreboard_url = 'https://www.espn.com/mens-college-basketball/scoreboard/_/group/50/date/'
espn_url = 'http://www.espn.com/college-football/boxscore?gameId='
espn_matchup_url = 'http://www.espn.com/college-football/matchup?gameId='
espn = 'https://www.espn.com/mens-college-basketball/scoreboard/_/group/50/date/20201209'


team_dict = {
		"Texas Christian": "TCU",
		"Nevada-Las Vegas": "UNLV",
		"Ohio State": "OSU",
		"Ohio St": "OSU",
		"Louisiana-Lafayette": "LA-Lafayette",
		'Louisiana': 'LA-Lafayette',
		'Louisiana Ragin Cajuns':'LA-Lafayette',
		'LA Lafayette': 'LA-Lafayette',
		"Middle Tennessee State": "Mid Tennessee",
		"Middle Tennessee St.": "Mid Tennessee",
		"East Carolina": "ECU",
		"Eastern Michigan": "E Michigan",
		"East Michigan": "E Michigan",
		"South Florida": "USF",
		"Southern Mississippi": "Southern Miss",
		'Southern Mississippi Golden Eagles':'Southern Miss',
		"Virginia": "UVA",
		"Connecticut": "UConn",
		"Louisiana-Monroe": "UL Monroe",
		"North Carolina": "UNC",
		"Brigham Young": "BYU",
		"California": "Cal",
		"Virginia Tech": "VT",
		"Northern Illinois": "N Illinois",
		"New Mexico State": "New Mexico St",
		"Florida State": "FSU",
		"Florida St": "FSU",
		"North Carolina State": "North Carolina St",
		'NC State': 'North Carolina St',
		"Washington State": "Washington St",
		"Central Michigan": "Cent Michigan",
		"Bowling Green State": "Bowling Green",
		"Florida Atlantic": "FAU",
		"Louisiana Tech": "LA Tech",
		"Western Michigan": "W Michigan",
		"Florida International": "FIU",
		"Florida Intl": "FIU",
		"Western Kentucky": "W Kentucky",
		"West Kentucky": "W Kentucky",
		"Massachusetts": "UMass",
		"Southern California": "USC",
		"Southern Cal": "USC",
		"Louisiana State": "LSU",
		"Miami - Florida": "Miami (FL)",
		'Miami':'Miami (FL)',
		"California - Los Angeles": "UCLA",
		'California - Los Angel': 'UCLA',
		"Central Florida": "UCF",
		"Nevada - Reno": "Nevada",
		"Texas - El Paso": "UTEP",
		"UTEP Miners": "UTEP",
		"Southern Methodist": "SMU",
		"Mississippi": "Ole Miss",
		"Mississippi State": "Miss St",
		"Mississippi St": "Miss St",
		"Troy State": "Troy",
		"Louisiana - Lafayette": "LA-Lafayette",
		"Northeast Louisiana": "UL Monroe",
		"LA Monroe": "UL Monroe",
		"Alabama - Birmingham": "UAB",
		"Texas A&M;": "Texas A&M",
		"Nevada - Las Vegas": "UNLV",
		"Miami - Ohio": "Miami (OH)",
		"Pittsburgh": "Pitt",
		"Florida A&M;": "Florida A&M",
		"Southeast Louisiana": "SE Louisiana",
		'Southeastern Louisiana": "SE Louisiana'
		"Youngstown State": "Youngstown St",
		"Texas State - San Marcos": "Texas State",
		"Eastern Kentucky": "E Kentucky",
		"Sam Houston State": "Sam Houston",
		"Southern Illinois": "S Illinois",
		"Jacksonville State": "Jacksonville St",
		"Western Carolina": "W Carolina",
		"Texas-San Antonio": 'UTSA',
		'Texas - San Antonio': 'UTSA',
		'Prairie View AM':'Prairie View',
		'North Carolina AT': 'North Carolina A&T',
		'UNC Charlotte': 'Charlotte',
		'SUNY-Buffalo': 'Buffalo',
		'SUNY - Buffalo': 'Buffalo',
		'Georgia Southern': 'Ga Southern',
		'Texas AM': 'Texas A&M',
		'CLEM': 'Clemson',
		'Hawai\'i': 'Hawaii',
		'Tennessee - Chattanooga': 'Chattanooga',
		'Tennessee - Martin': 'UT Martin',
		'Alabama A&M;': 'Alabama A&M',
		'North Carolina - Charlot': 'Charlotte',
		'California - Davis': 'UC Davis',
		'North Carolina A&T;': 'North Carolina A&T',
		'Gardner - Webb':'Gardner-Webb',
		'California Poly': 'Cal Poly',
		'Northern Arizona': 'N Arizona',
		'Southeast Missouri State': 'SE Missouri St',
		'Virginia Military': 'VMI',
		'Charleston Southern': 'Charleston So',
		'Middle Tennessee': 'Mid Tennessee',
		'Middle Tenn St': 'Mid Tennessee',
		'Nicholls': 'Nicholls State',
		'Alabama State': 'Alabama St',
		'Bethune - Cookman': 'Bethune-Cookman',
		'Arkansas - Pine Bluff': 'Arkansas-Pine Bluff',
		'Boston Coll':'Boston College',
		'Georgia St': 'Georgia State',
		'San Jose St': 'San Jose State',
		'Boise St': 'Boise State',
		'San Diego St': 'San Diego State',
		'Penn St': 'Penn State',
		'Michigan St': 'Michigan State',
		'Oregon St': 'Oregon State',
		'Texas St': 'Texas State',
		'Oklahoma St': 'Oklahoma State',
		'Oklahoma State Cowboys': 'Oklahoma State',
		'Tulsa Golden Hurricane':'Tulsa',
		'Ball St': 'Ball State',
		'Colorado St': 'Colorado State',
		'North Carolina  St': 'North Carolina State',
		'Kent St': 'Kent State',
		'Arizona St': 'Arizona State',
		'Appalachian State': 'Appalachian St',
		'Appalachian State Mountaineers': 'Appalachian St',
		'Fresno St': 'Fresno State',
		'Utah St': 'Utah State',
		'Arkansas St': 'Arkansas State',
		'Iowa St': 'Iowa State',
		'South Alabama Jaguars':'South Alabama',
		'Army Black Knights':'Army',
		'Middle Tennessee Blue Raiders':'Mid Tennessee',
		'Arkansas State Red Wolves':'Arkansas State',
		'Memphis Tigers':'Memphis',
		'BYU Cougars':'BYU',
		'Navy Midshipmen':'Navy',
		'Florida Gators':'Florida',
		'Ole Miss Rebels':'Ole Miss',
		'Alabama Crimson Tide':'Alabama',
		'Missouri Tigers':'Missouri',
		'Auburn Tigers':'Auburn',
		'Kentucky Wildcats':'Kentucky',
		'Arkansas Razorbacks':'Arkansas',
		'Georgia Bulldogs':'Georgia',
		'South Carolina Gamecocks':'South Carolina',
		'Tennessee Volunteers':'Tennessee',
		'LSU Tigers':'LSU',
		'Mississippi State Bulldogs':'Miss St',
		'Texas A&M Aggies':'Texas A&M',
		'Vanderbilt Commodores':'Vanderbilt',
		'Oklahoma Sooners':'Oklahoma',
		'Texas Longhorns':'Texas',
		'Clemson Tigers':'Clemson',
		'Notre Dame Fighting Irish':'Notre Dame',
		'Coastal Carolina Chanticleers':'Coastal Carolina',
		'Iowa State Cyclones':'Iowa State',
		'Baylor Bears':'Baylor',
		'Louisiana Tech Bulldogs':'LA Tech',
		'Wake Forest Demon Deacons':'Wake Forest',
		'Louisville Cardinals':'Louisville',
		'Western Kentucky Hilltoppers':'W Kentucky',
		'Duke Blue Devils':'Duke',
		'North Carolina Tar Heels':'UNC',
		'Syracuse Orange':'Syracuse',
		'Florida State Seminoles':'FSU',
		'Georgia Tech Yellow Jackets':'Georgia Tech',
		'Kansas Jayhawks':'Kansas',
		'Charlotte 49ers':'Charlotte',
		'UAB Blazers':'UAB',
		'Miami Hurricanes':'Miami (FL)',
	}
